### ISSUE TITLE
Export failed with status code: 403

### ISSUE THREAD

**Issue by fncll** [iamwillbar/calibre-plugin-readwise#15]
Not sure if this plugin is dead, but FYI, when I attempt to export to Readwise using the toolbar button I receive the following error:

```
Export failed with status code: 403
```

Not sure where to look for more info to provide! I have configured the API key and, just in case, tried generating a new one and using it.

**Comment by FeralFlora** [comment]
Is this plugin abandoned?

**Comment by ashleyhindle** [comment]
I fixed this in PR #16 and in my fork - https://github.com/ashleyhindle/calibre-plugin-readwise

**Comment by tovivekmishra** [comment]
jus came here to Thanks Ashley and comment that plugin is working perfectly fine with this update in the new version

**Comment by tovivekmishra** [comment]
jus after posting above i am getting this -
calibre, version 7.7.0
ERROR: Unhandled exception: <b>AttributeError</b>:'NoneType' object has no attribute 'group'

calibre 7.7  embedded-python: True
Windows-10-10.0.22621-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.22621')
Python 3.11.5
Windows: ('10', '10.0.22621', 'SP0', 'Multiprocessor Free')
Interface language: None
EXE path: C:\Program Files\Calibre2\calibre.exe
Successfully initialized third party plugins: Readwise (1, 0, 3)
Traceback (most recent call last):
  File "calibre_plugins.readwise.main", line 79, in sync
  File "calibre_plugins.readwise.main", line 132, in calculatePosition
AttributeError: 'NoneType' object has no attribute 'group'
 last night it worked fine,now this...
